Update PSD statistical detector set in SEA action
NTIA/scos-actions pull request #105
Opened 2023-12-26 22:28 UTC by aromanielloNTIA

In the SEA action:
- Reduce PSD frequency resolution to 80 kHz from 16 kHz (FFT length 175 down from 875)
- Update detector set: add median and (25th, 75th, 90th, 95th, 99th, 99.9th, 99.99th) percentiles, detected per bin

2024-01-04 16:33 UTC, dboulware approved these changes

2024-01-04 16:37 UTC, dboulware requested changes
This looks good, but I think it should increase the version since these changes will break the old configs.

2024-01-04 17:04 UTC, aromanielloNTIA commented
Agreed, but left the version unchanged by this PR since we should bundle a release with other recent/ongoing PRs which will already bump the version. I can make this individually increment the version instead if you think that's better.

2024-01-05 15:22 UTC, dboulware approved these changes

2024-01-05 15:22 UTC, merged