Discover action types and pass Sensor through action call
NTIA/scos-actions pull request #109
Opened 2024-01-15 18:54 UTC by dboulware

This (in conjunction with the associated scos-sensor PR) fixes an architectural issue in scos sensor and enables loading of actions from a scos sensor config directory. The main changes within this PR are:
- Reverts scos-actions repo to purely APIs. All initialization is now performed in scos-sensor (or outside of scos-actions)
- Actions are no longer initialized with a signal analyzer and gps. Instead, they are only initialized with their parameters and the signal analyzer, gps, preselector, switches, location, and sensor definition/capabilities are passed into the action call method through a new Sensor class. 
- Calibration is given a new property is_default to identify that the calibration is the default calibration file rather than one generated from a lab based cal. 
- Adds register_sensor and register_signal_analzyer signals. 

While the behavior is not enforced within the code in this repo, the readme has also been updated to reflect that the discover module used by scos-sensor plugins should expose an actions and/or action_types dictionary. Finally, because of these changes, this increments the version of scos-actions to 8.0.0.

2024-01-15 19:29 UTC, dboulware commented
Not quite ready.

2024-01-16 18:53 UTC, aromanielloNTIA commented on scos_actions/status/__init__.py
> +from scos_actions.status.status_monitor import StatusMonitor
I believe this is unused and can be removed:

scos-sensor imports the StatusMonitor with

```python
from scos_actions.status.status_monitor import StatusMonitor
```

Line 3 in `scos_actions/status/__init__.py` is unnecessary unless this import is changed to:

```python
from scos_actions.status import StatusMonitor
```

2024-01-16 19:14 UTC, dboulware commented on scos_actions/actions/interfaces/action.py
> +    def configure_preselector(self, sensor: Sensor, params: dict):
Done in https://github.com/NTIA/scos-actions/commit/5d327218bc4c74a411388b8165ee8f1c31044f52

2024-01-16 19:15 UTC, dboulware commented on scos_actions/actions/interfaces/action.py
> +    def get_sigmf_builder(self, sensor: Sensor, schedule_entry: dict) -> None:
Done in https://github.com/NTIA/scos-actions/commit/5d327218bc4c74a411388b8165ee8f1c31044f52

2024-01-16 19:24 UTC, aromanielloNTIA commented on scos_actions/actions/monitor_sigan.py
> +    def __init__(self, parameters={"name": "monitor_sigan"}, gps=None):
Resolved in [a562915](https://github.com/NTIA/scos-actions/pull/109/commits/a56291574b281e4d9d03355b553db4f092d1d132)

2024-01-17 16:18 UTC, aromanielloNTIA commented on scos_actions/status/__init__.py
> +from scos_actions.status.status_monitor import StatusMonitor
No longer relevant

2024-01-17 16:20 UTC, aromanielloNTIA commented on scos_actions/discover/__init__.py
>      register_component_with_status.send(mock_sigan.__class__, component=mock_sigan)
No longer relevant

2024-01-17 16:32 UTC, dboulware commented on scos_actions/hardware/sensor.py
> +        gps: GPSInterface = MockGPS(),
Agreed. I changed it to None.

2024-01-17 16:37 UTC, aromanielloNTIA commented on scos_actions/actions/sync_gps.py
> +        self.sensor = sensor
Retracting this comment, using setters as done here is preferred

2024-01-17 16:42 UTC, aromanielloNTIA commented on scos_actions/hardware/mocks/mock_sigan.py
> +        if self._sensor_calibration is not None:
Resolved in [ee5ebb4](https://github.com/NTIA/scos-actions/pull/109/commits/ee5ebb46e145a6efcd99701b3681e859eca79eee)

2024-01-17 19:23 UTC, aromanielloNTIA commented on scos_actions/settings.py
> +DEFAULT_CALIBRATION_FILE = path.join(CONFIG_DIR, "default_calibration.json")
Resolved in [d3c169d](https://github.com/NTIA/scos-actions/pull/109/commits/d3c169dc37059b6f0aac9c5d2cbcfdabbbbf45b9)

2024-01-23 17:15 UTC, aromanielloNTIA requested changes
Looks good- see minor comments included below. I'm about to test on seadog01 in the meantime.

2024-01-23 17:15 UTC, aromanielloNTIA commented on scos_actions/hardware/sensor.py
> +    def __init__(
Recommend adding `Optional[]` around type hints in the `__init__` parameters, where applicable

2024-01-23 17:15 UTC, aromanielloNTIA commented on scos_actions/hardware/sensor.py
> +    ):
Recommend including an informative class docstring here- this is now a central object to the SCOS Sensor architecture and it would be helpful to know what's required, what "capabilities" should be, what a location dict should look like, etc.

2024-01-23 17:15 UTC, aromanielloNTIA commented on scos_actions/hardware/sensor.py
> +            self._capabilities = None
Line 86 can be un-indented a level and the `else` condition can be removed

2024-01-23 17:15 UTC, aromanielloNTIA commented on scos_actions/hardware/sensor.py
> +            return False
Perhaps include some logger warnings/statements and another condition to check for the existence of `self.preselector`. There are a least a few cases (listed) where this property should return `False` and there should be some distinguishing logs to help troubleshoot:

- Sensor has no preselector at all (`self.preselector is None`)
- Sensor has a preselector, but no capabilities provided. Preselector may be configurable, but necessary information was not provided to initialize the `Sensor`
- Sensor has a preselector, and capabilities were provided, but the capabilities do not have a `preselector` in the `sensor`
- Sensor has a preselector, and capabilities were provided, but the `preselector` does not have `rf_paths`

2024-01-23 17:57 UTC, aromanielloNTIA commented on scos_actions/hardware/mocks/mock_sigan.py
> +        super().__init__(sensor_cal, sigan_cal)
I believe `switches` is missing as a parameter in this call

2024-01-26 18:52 UTC, dboulware commented on scos_actions/hardware/sensor.py
> +            return False
As we discussed, I've modifed the property to simple return True if either the sensor capabilities or the preselector have multiple rf_paths and inluded log statement to indicate why the property is returning true or false. Additional validation of the preselector against the sensor definition will be provided in the future in a different method.

2024-01-26 18:53 UTC, dboulware commented on scos_actions/hardware/mocks/mock_sigan.py
> +        super().__init__(sensor_cal, sigan_cal)
fixed

2024-01-26 18:53 UTC, dboulware commented on scos_actions/hardware/sensor.py
> +            self._capabilities = None
fixed

2024-01-26 18:53 UTC, dboulware commented on scos_actions/hardware/sensor.py
> +    ):
Added docstrings.

2024-01-26 18:54 UTC, dboulware commented on scos_actions/hardware/sensor.py
> +    def __init__(
Added Optional and updated constructor to require a signal analyzer and capabilities.

2024-01-27 20:28 UTC, merged