Sea 178 test actions loading
NTIA/scos-actions pull request #110
Opened 2024-02-20 16:20 UTC by jhazentia

2024-03-13 19:07 UTC, dboulware commented on scos_actions/actions/acquire_sea_data_product.py
> +        self.cal_adjust = utils.get_parameter(CAL_ADJUST, params)
Might want to either check if the CAL_ADJUST param exists or catch the exception if it doesn't and set it to true.

2024-03-13 19:35 UTC, dboulware commented on scos_actions/hardware/mocks/mock_gps.py
> +    def __init__(self, sigan):
Why does this need a sigan?

2024-03-13 21:46 UTC, dboulware commented on scos_actions/configs/actions/test_SEA_CBRS_Measure_Baseline.yml
>    rf_path: antenna
I think this same rf_path: antenna param should be added to all of the test actions to allow them to work with a configurable preselector or without a preselector. Currently, they will all fail on a sensor if it has a configurable preselector.

2024-04-16 19:12 UTC, jhazentia commented on scos_actions/hardware/mocks/mock_gps.py
> +    def __init__(self, sigan):
Fixed in 91e3eff

2024-04-16 19:13 UTC, jhazentia commented on scos_actions/actions/acquire_sea_data_product.py
> +        self.cal_adjust = utils.get_parameter(CAL_ADJUST, params)
Fixed in d06098f

2024-04-16 19:19 UTC, jhazentia commented on scos_actions/configs/actions/test_SEA_CBRS_Measure_Baseline.yml
>    rf_path: antenna
Fixed in 8d205e5

2024-04-24 18:59 UTC, dboulware commented on scos_actions/hardware/sensor.py
> +    def check_sensor_overload(self, data) -> bool:
It looks like data is expected to be an ndarray? I suggest adding a type hint. Also, is there any danger that data could not be cast to np.complex64? I'm not sure.

2024-04-24 19:00 UTC, dboulware commented on scos_actions/hardware/sensor.py
> +        if self.sensor_calibration_data["compression_point"] is not None:
Suggest moving this above so you don't compute the avg power if you don't know the compression point.

2024-04-24 19:03 UTC, dboulware commented on scos_actions/hardware/sensor.py
> +        if self.sensor_calibration_data["compression_point"] is not None:
Looks like this is only called if there is compression_point so maybe the previous comment can be disregarded unless there is a chance check_sensor_overload could be called in a different flow.

2024-04-24 19:48 UTC, dboulware commented on scos_actions/discover/__init__.py
> +actions = {"logger": Logger()}
Should we remove logger from the actions? Not a big deal either way.

2024-04-24 19:48 UTC, dboulware requested changes
Looks good. See comments for a couple minor suggestions.

2024-04-26 02:54 UTC, merged