Separate on board calibrations, support additional loss to antenna, add disk usage to diagnostics
NTIA/scos-actions pull request #114
Opened 2024-03-19 15:09 UTC by dboulware

This introduces significant changes to the handling of calibrations to separate the calibrations performed on board from the initial calibration and introduces a new differential calibration (that cannot be updated) to add additional loss values to move the reference point to the antenna.  The y-factor action is updated to create a new sensor calibration if there isn't one, and only saves calibration updates to an onboard calibration file. Calibration annotations are updated in each action to appropriately adjust the gain, noise figure, and reference based on whether or not a differential calibration is used or not. In addition, the compression point is maintained from the initial calibration if present. Finally, this also updates the diagnostic metadata to include disk_usage.

2024-03-22 13:50 UTC, dboulware commented on scos_actions/actions/acquire_sea_data_product.py
> -    def run(self, iqdata: np.ndarray) -> list:
Restored

2024-03-22 13:50 UTC, dboulware commented on scos_actions/actions/acquire_single_freq_fft.py
> +        measurement_result["duration_ms"] = int(self.num_samples / sample_rate_Hz)
Corrected

2024-03-22 13:50 UTC, dboulware commented on scos_actions/actions/acquire_single_freq_tdomain_iq.py
> +        # measurement_result["calibration_datetime"] = (
Removed

2024-03-22 13:51 UTC, dboulware commented on scos_actions/actions/calibrate_y_factor.py
> +        # self.sensor.sensor_calibration.to_json()
removed

2024-03-22 13:52 UTC, dboulware commented on scos_actions/actions/interfaces/measurement_action.py
>          # Rename compression point keys if they exist
Removed no longer applicable text.

2024-03-22 13:53 UTC, dboulware commented on scos_actions/hardware/sensor.py
> +            logger.warning("Failed to recompute calibration data")
For now, I have left this as is.

2024-03-22 13:53 UTC, dboulware commented on scos_actions/hardware/sensor.py
> +        if one exists for this sensor, and "calibration terminal" will be the value
Updated to include differential cal.

2024-03-22 13:53 UTC, dboulware commented on scos_actions/actions/interfaces/measurement_action.py
> +            frequency=self.sensor.signal_analyzer.frequency,
Updated to use measurement_result

2024-03-22 15:37 UTC, dboulware commented on scos_actions/actions/acquire_single_freq_fft.py
> +        measurement_result["center_frequency_Hz"] = self.frequency_Hz
Deleted measurement_result["center_frequency_Hz"]

2024-03-22 21:57 UTC, dboulware commented on scos_actions/hardware/sensor.py
> +    def signal_analyzer(self) -> Optional[SignalAnalyzerInterface]:
For the signal_analyzer there are likely scenarios where it could become none.

2024-03-22 22:03 UTC, dboulware commented on scos_actions/hardware/sensor.py
> +    def signal_analyzer(self, sigan: Optional[SignalAnalyzerInterface]):
I think most could return None so I marked some more as Optional.

2024-03-22 22:04 UTC, dboulware commented on scos_actions/calibration/interfaces/calibration.py
> +TODO
added

2024-03-22 22:04 UTC, dboulware commented on scos_actions/calibration/sensor_calibration.py
> +TODO
added

2024-03-22 22:05 UTC, dboulware commented on scos_actions/calibration/sensor_calibration.py
> +        :param file_path: File path for saving the updated calibration data.
updated

2024-03-22 22:05 UTC, dboulware commented on scos_actions/calibration/sensor_calibration.py
> +        now_string = datetime.utcnow().isoformat(timespec="milliseconds") + "Z"
Done

2024-03-22 22:05 UTC, dboulware commented on scos_actions/calibration/tests/test_sensor_calibration.py
> +            sr, f, g -> Set values for the mock USRP
Done

2024-03-22 22:10 UTC, dboulware commented on scos_actions/calibration/tests/test_sensor_calibration.py
> +        assert file_utc_time.year == cal_time_utc.year
Updated to use a fixed initial cal date in the past.

2024-03-22 22:11 UTC, dboulware commented on scos_actions/calibration/tests/test_sensor_calibration.py
> +            sr_m, f_m, g_m -> Set values to use when calculating the expected value
Ran out of time to address this one. Perhaps @aromanielloNTIA could if you want it updated.

2024-03-25 14:43 UTC, jhazentia commented on scos_actions/calibration/sensor_calibration.py
> +    data that may be updated. Within scos-senso,``SensorCalibration``
small typo, change `scos-senso` to `scos-sensor`

2024-03-25 14:44 UTC, jhazentia commented on scos_actions/calibration/sensor_calibration.py
> +    class provides an implementation fo the update method to allow calibration
small typo, change `fo` to `for`

2024-03-25 17:07 UTC, jhazentia commented on scos_actions/calibration/sensor_calibration.py
> +        now = parse_datetime_iso_format_str(now_string)
I see, thanks.

2024-03-25 17:29 UTC, jhazentia commented on scos_actions/calibration/tests/test_sensor_calibration.py
> +            sr_m, f_m, g_m -> Set values to use when calculating the expected value
@aromanielloNTIA This is a minor issue and definitely not a blocker for this PR. Do you think this should be ignored or fixed now or later?

2024-03-25 20:24 UTC, jhazentia requested changes
Just some minor comments remaining.

2024-03-25 21:12 UTC, aromanielloNTIA commented on scos_actions/calibration/utils.py
> +    allows for value ``1`` to match a key ``"1.0"``.
Added to docstring in cf1175c08782f6e80336f700ac611b4e66f65280

2024-03-25 21:17 UTC, aromanielloNTIA commented on scos_actions/calibration/utils.py
> +            + f"\nUsing calibration data: {calibrations}"
Added another condition to format the debug message in ae416030e409b3946bed725ae07680e4ed428f6e, then noticed that the existing condition was incorrect and fixed it in 59322059b106c70357b7938d5f09e41395775601

2024-03-25 21:19 UTC, aromanielloNTIA commented on scos_actions/calibration/sensor_calibration.py
> +    data that may be updated. Within scos-senso,``SensorCalibration``
Fixed typo in fc2d32ad44ebf1f33e60e04ff1a7edea8f531cab

2024-03-25 21:20 UTC, aromanielloNTIA commented on scos_actions/calibration/sensor_calibration.py
> +    class provides an implementation fo the update method to allow calibration
Corrected typo in bcea100f3287d0d6362350b4e0af36da9e0bf7c8

2024-03-25 21:21 UTC, aromanielloNTIA commented on scos_actions/actions/interfaces/measurement_action.py
> +        sensor_cal = self.sensor.sensor_calibration_data
Removed unused variable in 5f9643d7bf755b401a76b940c907b3f29d6ee93b

2024-03-25 21:42 UTC, aromanielloNTIA commented on scos_actions/calibration/utils.py
> +            + f"\nUsing calibration data: {calibrations}"
I made some improvements to this in 73fab880d4e065e7fecfcf2eb44f852071ed3d1c to ensure that the same conditions which actually dictate the lookup are logged, and made the logs more informative. Updated unit tests accordingly.

2024-03-25 21:57 UTC, aromanielloNTIA commented on scos_actions/calibration/tests/test_sensor_calibration.py
> +            sr_m, f_m, g_m -> Set values to use when calculating the expected value
This part of the calibration testing is outdated now, and essentially is only used to check the generation of the dummy calibration used by the test class. I removed it in 15348fd4dbd2cc51be08d0a64a9b9c9c101ea394 - removing this also made `easy_gain` unused, so I removed it as well.

2024-03-27 16:43 UTC, jhazentia approved these changes

2024-03-27 16:43 UTC, merged