Make actions set RF path
NTIA/scos-actions pull request #36
Opened 2022-08-25 21:46 UTC by aromanielloNTIA

Addresses #35 

- Add `rf_path` as a required configuration parameter for time domain IQ and single frequency FFT actions if a preselector is defined in the sensor definition file
- Set the configured `rf_path` before measurement in time domain IQ and single frequency FFT actions

YAML configs will need to be updated in order to run these actions using a preselector.

2022-08-29 14:58 UTC, dboulware requested changes
Most of these changes are not needed as the existing implementation will handle setting the preselector state if rf_path is in the measurement params. I would recommend we get rid of the unnecessary changes, keep the changes in settings, and consider raising an exception in the base actions configure_preselector method if the sensor has a preselector and no rf_path is specified in the measurment params, or perhaps if the preselector has multiple paths and no rf path is specified.

2022-08-29 14:58 UTC, dboulware commented on scos_actions/actions/acquire_stepped_freq_tdomain_iq.py
> +            if HAS_PRESELECTOR:
This will be handled below in the call to configure.

2022-08-29 15:48 UTC, aromanielloNTIA commented on scos_actions/actions/acquire_single_freq_fft.py
> +        if HAS_PRESELECTOR:
Wouldn't this require the configs to look something like:

```yaml
...
rf_path: {"rf_path": "antenna"}
...
```

instead of

```yaml
...
rf_path: antenna
```
...

2022-08-29 17:23 UTC, aromanielloNTIA commented on scos_actions/actions/acquire_single_freq_fft.py
> +        if HAS_PRESELECTOR:
I understand your point about the redundancy of the `HAS_PRESELECTOR` check, but I just want to confirm that you're only saying to remove that conditional, and not the construction of the RF path dictionary underneath it.

2022-08-29 19:19 UTC, dboulware commented on scos_actions/actions/acquire_single_freq_fft.py
> +        if HAS_PRESELECTOR:
The dictionary should not be needed either. As is, configure should be being called with the dictionary of all of the parameters from the yaml as a dictionary and configure calls configure_preselector with the same dictionary which should include base_url key.

2022-09-01 14:44 UTC, dboulware requested changes
Just a few minor changes. See in-line comments.

2022-09-01 14:44 UTC, dboulware commented on scos_actions/actions/acquire_single_freq_tdomain_iq.py
> +RF_PATH = MeasurementAction.PRESELECTOR_PATH_KEY
No longer used.

2022-09-01 14:44 UTC, dboulware commented on scos_actions/actions/acquire_stepped_freq_tdomain_iq.py
> +RF_PATH = SingleFrequencyTimeDomainIqAcquisition.PRESELECTOR_PATH_KEY
No longer used.

2022-09-01 14:44 UTC, dboulware commented on scos_actions/actions/interfaces/action.py
> +            if len(preselector.__get_rf_paths()) != 1:
change to len(preselector.rf_paths)

2022-09-01 17:32 UTC, aromanielloNTIA commented on scos_actions/actions/acquire_single_freq_tdomain_iq.py
> +RF_PATH = MeasurementAction.PRESELECTOR_PATH_KEY
Fixed in [358d47e](https://github.com/NTIA/scos-actions/pull/36/commits/358d47e1e7f684f3f36b26a2c403a842fc2f1f84)

2022-09-01 17:32 UTC, aromanielloNTIA commented on scos_actions/actions/acquire_stepped_freq_tdomain_iq.py
> +RF_PATH = SingleFrequencyTimeDomainIqAcquisition.PRESELECTOR_PATH_KEY
Fixed in [358d47e](https://github.com/NTIA/scos-actions/pull/36/commits/358d47e1e7f684f3f36b26a2c403a842fc2f1f84)

2022-09-01 17:32 UTC, aromanielloNTIA commented on scos_actions/actions/interfaces/action.py
> +            if len(preselector.__get_rf_paths()) != 1:
Changed in [65c5b40](https://github.com/NTIA/scos-actions/pull/36/commits/65c5b40e470e74e0673feaa9b41e7b93d1114dd1)

2022-09-01 18:19 UTC, dboulware requested changes

2022-09-01 18:19 UTC, dboulware commented on scos_actions/settings.py
> +    if "preselector" in SENSOR_DEFINITION_FILE:
Sorry, I just noticed SENSOR_DEFINITION_FILE is the file path so this check won't work. capabilities/__init__.py loads the sensor definition file into capabilities. You would have to check if "preselector" in capabilities["sensor"], but that check can't be performed here or in utils. The base Action class already imports capabilities so I'd probably be inclined to add has_preselector property in there and set it in the constructor.

2022-09-01 18:26 UTC, aromanielloNTIA commented on scos_actions/settings.py
> +    if "preselector" in SENSOR_DEFINITION_FILE:
Fixed in[62b3f85](https://github.com/NTIA/scos-actions/pull/36/commits/62b3f85c91cd53cc5395e5ce4b4d92c4dcd5089e)

2022-09-06 17:35 UTC, dboulware commented on scos_actions/actions/interfaces/action.py
> +        elif self.has_preselector:
Don't call .__get_rf_paths() in the debug statement. Use preselector.rf_path[0].name instead if you keep it in there. But, I would also probably change the debug statement and the comment above because it doesn't actually set the preselector path. It just ignores it.

2022-09-06 17:53 UTC, aromanielloNTIA commented on scos_actions/actions/interfaces/action.py
> +        elif self.has_preselector:
Oops, added the debug message there but forgot the actual code to set the path. On second thought, though, let's just make it so that the RF path _must_ be specified. I'll remove this bit entirely, so that an RF path must be specified in the YAML config when the sensor has a preselector.

2022-09-06 17:55 UTC, aromanielloNTIA commented on scos_actions/actions/interfaces/action.py
> +        elif self.has_preselector:
Done in [9912244](https://github.com/NTIA/scos-actions/pull/36/commits/991224495b35dc13b6612261036414e076771418)

2022-09-08 13:33 UTC, dboulware reviewed
Looks good.

2022-09-08 15:42 UTC, merged