SEA Action: thread safety and garbage collection improvements
NTIA/scos-actions pull request #77
Opened 2023-04-25 23:47 UTC by aromanielloNTIA

#### Changes
- Add garbage collection to limit memory usage.
- Bump dependency version: `ray>=2.4.0`
- Add explicit initialization of Ray (previously initialized silently by the first call to a Ray function)
- Reduce FFT workers to 1, since the FFT task is already running in parallel with other tasks
- Remove logging from `signal_processing` functions (except calibration) for automatic thread safety in parallel processing applications. Some logger messages are replaced with exceptions, others are removed.
- Add the `ntia-core:classification` field to SEA metadata, per NTIA/sigmf-ns-ntia#40

#### Memory management testing:
I ran a lot of testing on seadog02, using tooling from `ray[default]`. Memory is properly freed following each action run, and IQ is freed from memory after it is no longer needed. At most, 3 IQ arrays are kept in memory at once. Typically, only 1 or 2 IQ arrays are kept in memory at once.

2023-05-04 19:50 UTC, jhazentia commented on scos_actions/actions/acquire_sea_data_product.py
> +        yield [worker.run.remote(iqdata) for worker in self.workers]
is yield just being used here to execute the last 2 lines of code afterward instead of returning immediately?

2023-05-04 20:29 UTC, jhazentia requested changes
1 test is failing.

2023-05-04 20:42 UTC, jhazentia commented on scos_actions/actions/acquire_sea_data_product.py
> +        yield [worker.run.remote(iqdata) for worker in self.workers]
If this is intended for creating a generator to save memory, I think it would need yield each element rather than the whole list, but not sure how that would affect running the remote workers

2023-05-04 20:49 UTC, aromanielloNTIA commented on scos_actions/actions/acquire_sea_data_product.py
> +        yield [worker.run.remote(iqdata) for worker in self.workers]
Your comment made me notice the incorrect comment on line 418. I fixed that in 584f5f94ff456604948ab50aedd97bc07a78ba50
To your question, yes. This is based on [this example](https://docs.ray.io/en/latest/ray-core/patterns/generators.html). Even though the returned object is not huge, this approach should help with memory management. It also avoids unnecessarily calling `ray.get` here, see [this example](https://docs.ray.io/en/latest/ray-core/patterns/unnecessary-ray-get.html). The `IQProcessor.run()` will do IIR filtering, hand off the data for processing, and immediately return. Even during the filtering, the loop in `__call__` is able to proceed to the next IQ capture, since the `IQProcessor` is still a Ray remote actor. The two lines you're talking about should be unnecessary (and testing with `ray memory` supports this), but regularly doing this explicitly helps (redundantly, it seems) protect against [this issue](https://stackoverflow.com/questions/55749394/how-to-fix-the-constantly-growing-memory-usage-of-ray).

2023-05-05 18:42 UTC, jhazentia commented on scos_actions/signal_processing/apd.py
>          all_amps = np.abs(time_data)
does this need `.real` like the NumExpr version?

2023-05-05 19:45 UTC, jhazentia commented on scos_actions/signal_processing/tests/test_unit_conversion.py
> +        elif isinstance:
It looks like some arguments to `isinstance` are missing here

2023-05-05 19:50 UTC, jhazentia commented on scos_actions/signal_processing/tests/test_unit_conversion.py
> +        elif isinstance:
It looks like some arguments to isinstance are missing here

2023-05-05 19:52 UTC, jhazentia commented on scos_actions/signal_processing/tests/test_unit_conversion.py
> +        elif isinstance:
Same for other tests in this file

2023-05-05 20:22 UTC, jhazentia commented on scos_actions/signal_processing/tests/test_unit_conversion.py
> +            test_convert(int(v), c)
this will never get executed as `v` is never 1

2023-05-05 20:29 UTC, jhazentia commented on scos_actions/signal_processing/tests/test_unit_conversion.py
> +            test_convert(int(v), c)
Also check this in other tests

2023-05-08 14:37 UTC, aromanielloNTIA commented on scos_actions/signal_processing/apd.py
>          all_amps = np.abs(time_data)
No- the NumPy version using `np.abs` will yield real floating point instead of complex representation. The NumExpr version still has the same data type in the result without using `.real` - so you end up carrying around a bunch of zero-d out imaginary components.

2023-05-08 14:40 UTC, aromanielloNTIA commented on scos_actions/signal_processing/tests/test_unit_conversion.py
> +        elif isinstance:
Thanks for catching- should be `else` instead of `elif` here. Fixed in 7f7c37c5851cc1ce56c05ba6f800a63bc414a96f

2023-05-08 14:46 UTC, aromanielloNTIA commented on scos_actions/signal_processing/tests/test_unit_conversion.py
> +            test_convert(int(v), c)
Fixed this for a handful of similar cases in that file in 5caf4f7f9b954fd4e112c98c69211bfdf4d51b7d

I also switched to using `np.isclose` instead of `==` in some places to avoid test failure due to minuscule floating point precision errors.

2023-05-08 20:20 UTC, jhazentia approved these changes

2023-05-08 20:38 UTC, merged