Fix operand array error
NTIA/scos-actions pull request #79
Opened 2023-05-09 16:47 UTC by dboulware

This fixes a bug caused by passing in a read only array into the fft routine. The fix creates a new empty array for the output that matches the shape and datatype of the array passed in.

2023-05-09 17:19 UTC, jhazentia approved these changes

2023-05-09 21:37 UTC, jhazentia requested changes
It looks like this is failing tests

2023-05-10 17:25 UTC, aromanielloNTIA commented
The tests fail because in Doug's changes, if there is no FFT windowing, then the FFT is performed on an empty array. I suggest making a copy of the array instead, and only doing so when needed (i.e., in the case where windowing is applied and the input data is large enough that NumExpr will be used to do so). I can make this change and update the tests to cover the read-only input data case. I will also check to see if a similar problem pops up elsewhere where NumExpr is used.

2023-05-10 17:47 UTC, aromanielloNTIA commented
I did not see the same problem happening with NumExpr usage inside other signal processing functions. However, I modified signal processing unit tests so that all tests for functions which use NumExpr for large arrays will be tested with read-only array inputs. This should help catch any similar problem in the future. All tests are passing now.

2023-05-10 18:41 UTC, jhazentia commented on scos_actions/signal_processing/tests/test_apd.py
>          min_bin = np.nanmin(ne.evaluate("20*log10(abs(example_iq_data).real)"))
inside the for loop, example_iq_data should be changed to iq

2023-05-10 18:45 UTC, aromanielloNTIA commented on scos_actions/signal_processing/tests/test_apd.py
>          min_bin = np.nanmin(ne.evaluate("20*log10(abs(example_iq_data).real)"))
Fixed in 23bb18b7a97a6a13cc85636413d8747f71b1165b

Tests all pass

2023-05-10 19:22 UTC, jhazentia approved these changes

2023-05-10 19:51 UTC, merged