Update metadata handling for SigMF-NS-NTIA updates
NTIA/scos-actions pull request #83
Opened 2023-06-14 19:01 UTC by aromanielloNTIA

- Update metadata based on changes from NTIA/sigmf-ns-ntia#42 for single frequency IQ, stepped frequency IQ, single frequency M4S, and NASCTN SEA actions
- Bring sensor definition files closer in-line with the `ntia-sensor` specification. Now, they only differ by the fact that the sensor definition file may include a `"location"` object (which has not been altered). When the sensor definition is loaded, any location data is removed from the sensor definition dictionary and made available as a GeoJSON Point-formatted dict, `SENSOR_LOCATION`, for use elsewhere. 
- Add useful metadata generating base methods to abstract action classes
- Metadata interfaces are created, leveraging [msgspec](https://jcristharif.com/msgspec/). These may eventually roll into a dedicated Python package for sigmf-ns-ntia.

**NOTE: Still testing**
Draft PR available for initial review of major changes. Still need to update tests ("TODO" comments are in place where additions are planned), and test IQ and M4S actions.

2023-06-20 20:53 UTC, dboulware requested changes
Looks good. See in-line suggestions and comments.

2023-06-20 20:53 UTC, dboulware commented on scos_actions/metadata/interfaces/ntia_sensor.py
> +    sensor_spec: Optional[HardwareSpec]
Should sensor_spec not be optional?

2023-06-20 20:53 UTC, dboulware commented on scos_actions/metadata/interfaces/ntia_scos.py
> +    name: Optional[str]
Should name not be optional?

2023-06-20 20:53 UTC, dboulware commented on scos_actions/metadata/interfaces/ntia_scos.py
> +    id: Optional[str]
Should id and name not be optional?

2023-06-20 20:53 UTC, dboulware commented on scos_actions/metadata/interfaces/ntia_algorithm.py
> +    filter_type: Optional[FilterType]
Should id and filter_type not be optional?

2023-06-20 20:53 UTC, dboulware commented on scos_actions/metadata/interfaces/ntia_algorithm.py
> +    name: Optional[str]
Should name not be optional?

2023-06-20 20:53 UTC, dboulware commented on scos_actions/metadata/interfaces/ntia_algorithm.py
> +    id: Optional[str]
Should id not be optional?

2023-06-22 16:15 UTC, aromanielloNTIA commented on scos_actions/actions/acquire_single_freq_fft.py
> +            reference="preselector input",
This mirrors the previous behavior: see [here](https://github.com/NTIA/scos-actions/blob/6278878dba5996f87b90f0da8e5efc25cd006cc6/scos_actions/actions/acquire_single_freq_fft.py#L261).

I implemented this a bit better in 98aad41d303b3c08cfe605ea906ea0b3900dbdd3. The new behavior is dependent on the "calibration_adjust" parameter. If the IQ data is scaled using calibration data, the reference is set to "calibration terminal". If not, the reference is set to "signal analyzer input".

2023-06-22 16:16 UTC, aromanielloNTIA commented on scos_actions/actions/acquire_single_freq_fft.py
> +            name="M4S Detector Result",
I don't think so- the M4S result (as it currently exists/has existed) is not actually a power spectral _density_ since the power scaling is not "dBm/Hz". It's a minor difference, but that's also part of the reason for the generalized `Graph` approach in the metadata updates: we are able to support both types of processed data using the same metadata object.

2023-06-22 16:38 UTC, aromanielloNTIA commented on scos_actions/actions/acquire_single_freq_fft.py
Made this change in e28bc94d59303c69e17f0b6885cf44abcf209328. This commit also renames "create_power_detector" and "apply_power_detector" to "create_statistical_detector" and "apply_statistical_detector"

Detectors probably don't have to be Enum's at this point, but I've left it that way for now. The only difference in the enum names and values are that the values for "min" and "max" are "minimum" and "maximum". The Enum really just enforces consistent detector ordering, which we could do using a list instead. Or even a mapping of detector names to the functions which are used (e.g, "np.median()") . I don't think we need to worry about those changes for now.

2023-06-22 16:39 UTC, aromanielloNTIA commented on scos_actions/actions/acquire_single_freq_fft.py
Sidenote, I think it makes sense to keep the "statistical_detector" functions within the `power_analysis` module, at least for now.

2023-06-22 16:45 UTC, aromanielloNTIA commented on scos_actions/metadata/interfaces/ntia_sensor.py
> +    id: Optional[str]
Yep, good catch- fixed in 89c4f5923cb7907a05abbf3f8654f93a0e16d403

2023-06-22 16:50 UTC, aromanielloNTIA commented on scos_actions/metadata/interfaces/ntia_scos.py
> +    name: Optional[str]
Yes, fixed in 7efd48ec2bdc42e6d4d22e3b9a3a6e372d2631c3

2023-06-22 16:50 UTC, aromanielloNTIA commented on scos_actions/metadata/interfaces/ntia_scos.py
> +    id: Optional[str]
Yes, fixed in 7efd48ec2bdc42e6d4d22e3b9a3a6e372d2631c3

2023-06-22 16:50 UTC, aromanielloNTIA commented on scos_actions/metadata/interfaces/ntia_algorithm.py
> +    filter_type: Optional[FilterType]
Yes, fixed in 7efd48ec2bdc42e6d4d22e3b9a3a6e372d2631c3

2023-06-22 16:50 UTC, aromanielloNTIA commented on scos_actions/metadata/interfaces/ntia_algorithm.py
> +    name: Optional[str]
Yes, fixed in 7efd48ec2bdc42e6d4d22e3b9a3a6e372d2631c3

2023-06-22 16:50 UTC, aromanielloNTIA commented on scos_actions/metadata/interfaces/ntia_algorithm.py
> +    id: Optional[str]
Yes, fixed in 7efd48ec2bdc42e6d4d22e3b9a3a6e372d2631c3 (along with other required fields in the DFT object)

2023-06-22 18:36 UTC, dboulware requested changes
Looks good. Update version and it should be good to go.

2023-06-22 20:06 UTC, merged